export const users = [
  { username: "mimifaulks", password: "Swede8562" },
  { username: "joworthy", password: "Broccoli822" },
  { username: "lisatownsend", password: "Celeriac9725" },
  { username: "sarahbarker", password: "Radish506" },
  { username: "gailclayton", password: "Beetroot864" },
  { username: "natashawillenbrook", password: "Asparagus1246" },
  { username: "starharford", password: "Cauliflower97" },
  { username: "katieangotti", password: "Tomato22" },
  { username: "letsgrowtrialist1", password: "Lettuce908" },
  { username: "letsgrowtrialist2", password: "Cucumber6040" },
  { username: "letsgrowtrialist3", password: "Chard0099" },
  { username: "letsgrowtrialist4", password: "Avocado67" },
  { username: "letsgrowtrialist5", password: "Aubergine1292" },
  { username: "letsgrowtrialist6", password: "Spianch866" },
  { username: "letsgrowtrialist7", password: "Okra11" },
  { username: "faye@polkadotfarm.co.uk", password: "Radish1200" },
  { username: "charlotte@polkadotfarm.co.uk", password: "Carrot2039" },
]
