export const users = [
  { username: "mimifaulks", password: "Swede8562", trial: false },
  { username: "missinsley", password: "Tomato525", trial: true },
  { username: "missfaulkner", password: "Carrot974", trial: true },
  { username: "jesshines", password: "Spud9725", trial: true },
  { username: "natashabardney", password: "Pepper864", trial: true },
  { username: "misshann", password: "Potato522", trial: true },
  { username: "ailsausher", password: "Cabbage837", trial: true },
  { username: "katestarkie", password: "Lettuce562", trial: true },
  { username: "kathryndriver", password: "Parsnip927", trial: true },
  { username: "joworthy", password: "Broccoli822", trial: true },
  { username: "sahiraarshad", password: "Brussels752", trial: true },
  { username: "nathalielongstaff", password: "Kale23525", trial: true },
  { username: "missdodd", password: "Celeriac972", trial: true },
  { username: "natashaparkinson", password: "Cauliflower97", trial: true },
  { username: "angelaauld", password: "Pickle1246", trial: true },
  { username: "nicoladanielsgreen", password: "Avocado397", trial: true },
  { username: "samanthawalker", password: "Savoy9742", trial: true },
]
